port: "{your port}"

db:
  username: "{your username}"
  host: "{your host}"
  port: "{your port}"
  dbname: "{your dbname}"
  password: "{your password}"
  sslmode: "disable"

auth:
  sha_salt: "{your salt}"
  jwt_signing_key: "{your key}"
  jwt_token_ttl: "{your ttl in hours}"